version: '3.8'

services:
  discord-bot:
    build: .
    container_name: discord-voice-scribe
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./recordings:/app/recordings
      - ./data:/app/data
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - DATABASE_PATH=/app/data/recordings.db
      - RECORDINGS_PATH=/app/recordings
      - WEB_SERVER_HOST=0.0.0.0
      - WEB_SERVER_PORT=8000
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3